import type { LanguageRegistration } from "shiki/core";
import type { ShikiLanguageId } from "./language-map";

/**
 * Lazy loaders for every Shiki grammar the code viewer supports. Each entry is
 * a separate dynamic import, so a grammar is only downloaded the first time a
 * file in that language is opened.
 */
export type LanguageLoader = () => Promise<{ default: LanguageRegistration[] }>;

export const SHIKI_LANGUAGE_LOADERS: Record<ShikiLanguageId, LanguageLoader> = {
  typescript: () => import("shiki/langs/typescript.mjs"),
  tsx: () => import("shiki/langs/tsx.mjs"),
  javascript: () => import("shiki/langs/javascript.mjs"),
  jsx: () => import("shiki/langs/jsx.mjs"),
  python: () => import("shiki/langs/python.mjs"),
  java: () => import("shiki/langs/java.mjs"),
  go: () => import("shiki/langs/go.mjs"),
  rust: () => import("shiki/langs/rust.mjs"),
  c: () => import("shiki/langs/c.mjs"),
  cpp: () => import("shiki/langs/cpp.mjs"),
  csharp: () => import("shiki/langs/csharp.mjs"),
  "objective-c": () => import("shiki/langs/objective-c.mjs"),
  swift: () => import("shiki/langs/swift.mjs"),
  kotlin: () => import("shiki/langs/kotlin.mjs"),
  scala: () => import("shiki/langs/scala.mjs"),
  groovy: () => import("shiki/langs/groovy.mjs"),
  ruby: () => import("shiki/langs/ruby.mjs"),
  php: () => import("shiki/langs/php.mjs"),
  perl: () => import("shiki/langs/perl.mjs"),
  lua: () => import("shiki/langs/lua.mjs"),
  dart: () => import("shiki/langs/dart.mjs"),
  elixir: () => import("shiki/langs/elixir.mjs"),
  erlang: () => import("shiki/langs/erlang.mjs"),
  haskell: () => import("shiki/langs/haskell.mjs"),
  ocaml: () => import("shiki/langs/ocaml.mjs"),
  fsharp: () => import("shiki/langs/fsharp.mjs"),
  clojure: () => import("shiki/langs/clojure.mjs"),
  r: () => import("shiki/langs/r.mjs"),
  julia: () => import("shiki/langs/julia.mjs"),
  zig: () => import("shiki/langs/zig.mjs"),
  nim: () => import("shiki/langs/nim.mjs"),
  solidity: () => import("shiki/langs/solidity.mjs"),
  vue: () => import("shiki/langs/vue.mjs"),
  svelte: () => import("shiki/langs/svelte.mjs"),
  astro: () => import("shiki/langs/astro.mjs"),
  shellscript: () => import("shiki/langs/shellscript.mjs"),
  powershell: () => import("shiki/langs/powershell.mjs"),
  bat: () => import("shiki/langs/bat.mjs"),
  asm: () => import("shiki/langs/asm.mjs"),
  sql: () => import("shiki/langs/sql.mjs"),
  graphql: () => import("shiki/langs/graphql.mjs"),
  proto: () => import("shiki/langs/proto.mjs"),
  wasm: () => import("shiki/langs/wasm.mjs"),
  html: () => import("shiki/langs/html.mjs"),
  css: () => import("shiki/langs/css.mjs"),
  scss: () => import("shiki/langs/scss.mjs"),
  sass: () => import("shiki/langs/sass.mjs"),
  less: () => import("shiki/langs/less.mjs"),
  xml: () => import("shiki/langs/xml.mjs"),
  markdown: () => import("shiki/langs/markdown.mjs"),
  mdx: () => import("shiki/langs/mdx.mjs"),
  rst: () => import("shiki/langs/rst.mjs"),
  json: () => import("shiki/langs/json.mjs"),
  jsonc: () => import("shiki/langs/jsonc.mjs"),
  json5: () => import("shiki/langs/json5.mjs"),
  yaml: () => import("shiki/langs/yaml.mjs"),
  toml: () => import("shiki/langs/toml.mjs"),
  ini: () => import("shiki/langs/ini.mjs"),
  dotenv: () => import("shiki/langs/dotenv.mjs"),
  properties: () => import("shiki/langs/properties.mjs"),
  dockerfile: () => import("shiki/langs/dockerfile.mjs"),
  make: () => import("shiki/langs/make.mjs"),
  cmake: () => import("shiki/langs/cmake.mjs"),
  nix: () => import("shiki/langs/nix.mjs"),
  hcl: () => import("shiki/langs/hcl.mjs"),
  terraform: () => import("shiki/langs/terraform.mjs"),
};
